# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  displayName: 'npm ci'
  inputs:
    command: 'custom'
    customCommand: 'ci'
- task: Npm@1
  displayName: 'npm run lint'
  inputs:
    command: 'custom'
    customCommand: 'run lint'
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: 'custom'
    customCommand: 'run build'
- task: Npm@1
  displayName: 'npm run test'
  inputs:
    command: 'custom'
    customCommand: 'run test'
- task: PublishCodeCoverageResults@1
  displayName: 'capture code coverage'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
- task: Npm@1
  displayName: 'npm run dist (master only)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: 'custom'
    customCommand: 'run dist'
- task: GitHubRelease@0
  displayName: 'tag release (master only)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    gitHubConnection: 'github - bengreenier'
    repositoryName: 'rtc-dialtone/trunkline'
    action: 'create'
    target: 'v$(Build.SourceVersion)'
    tagSource: 'auto'
    title: 'v$(Build.SourceVersion)'
    assets: '$(System.DefaultWorkingDirectory)/bin/**'
